# Generated by Django 4.2.2 on 2023-06-09 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_player_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broomstick',
            name='player',
        ),
        migrations.AddField(
            model_name='team',
            name='broomsticks',
            field=models.ManyToManyField(to='main_app.broomstick'),
        ),
    ]
