# Generated by Django 4.2.2 on 2023-06-09 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_broomstick_player_team_broomsticks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='alive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='hogwarts_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='hogwarts_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='wizard',
            field=models.BooleanField(default=False),
        ),
    ]
