# Generated by Django 4.2.2 on 2023-06-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_player_alive_alter_player_hogwarts_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broomstick',
            name='choice',
            field=models.CharField(choices=[('AWG', 'Air Wave Gold'), ('ASF', 'Australian Flyabout'), ('BBTL', 'Bluebottle'), ('CS1', 'Cleansweep One'), ('CS2', 'Cleansweep Two'), ('CS3', 'Cleansweep Three'), ('CS5', 'Cleansweep Five'), ('CS6', 'Cleansweep Six'), ('CS7', 'Cleansweep Seven'), ('CS11', 'Cleansweep Eleven'), ('C140', 'Comet 140'), ('C180', 'Comet 180'), ('C220', 'Comet 220'), ('C260', 'Comet 260'), ('C290', 'Comet 290'), ('FBLT', 'Firebolt'), ('FBLTS', 'Firebolt Supreme'), ('MNTM', 'Moontrimmer'), ('N1000', 'Nimbus 1000'), ('N1001', 'Nimbus 1001'), ('N1500', 'Nimbus 1500'), ('N1700', 'Nimbus 1700'), ('N2000', 'Nimbus 2000'), ('N2001', 'Nimbus 2001'), ('OKS79', 'OAKSHAFT 79'), ('SS', 'Shooting Star'), ('SIBA', 'Siberian Arrow'), ('SILVA', 'Silver Arrow'), ('SS21', 'Starsweeper XXI'), ('SST', 'Swiftstick'), ('TB7', 'Thunderbolt VII'), ('TBL', 'Tinderblast'), ('TVB', 'Transylvanian Barb'), ('TB30', 'Turbo XXX'), ('TW90', 'Twigger 90'), ('VARA', 'Varápidos'), ('YAJI', 'Yajirushi')], default='AWG', max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
